 Nbits=4; %Numero de bits
 Cu=1; % Capacitancia Unitaria
 sigmaCu=0; % desviacion est�ndar de la capacitancia unitaria
 Vdd=8; % Tensi�n de referencia positiva
 Vss=-8; % Tensi�n de referencia negativa
 Vcm=(Vdd-Vss)/2; %Tension de modo com�n
 Vin=7
 VinP=Vin/2  + Vcm;
 VinN=-Vin/2 + Vcm;
 [BITS]=SAR_ADC(Nbits,Cu,sigmaCu,Vdd, Vss, VinP, VinN, Vcm)
